### ISSUE TITLE
Error message when Kodi boots up

### ISSUE THREAD

**Issue by rizreflects** [Zaxxon709/accountmanager#57] opened 2024-12-04 11:22 UTC
Hey there friend. For the past 2 days I have encountered an error message from account manager each time Kodi starts up. Nothing seems to be affected, e.g. my accounts are all still working perfectly fine and are synced up correctly. But the error message still appears and I'm unsure why. It's never happened before and I've been using this addon since the day you first created it. I've attached my log so you can have a better look at it, as I unfortunately do not know what the problem may be. Any help would be appreciated. Thanks a lot.

https://paste.kodi.tv/alopinotiv

**Comment by rizreflects** [comment] 2024-12-04 11:24
2024-12-04 11:15:16.826 T:22196 info <general>: [ script.module.accountmgr ] Could not connect to remote repo XML: status code = 404 2024-12-04 11:15:17.296 T:22196 info <general>: [ script.module.accountmgr ] Debrid Account Expiry Notification Service Starting... 2024-12-04 11:15:17.743 T:22196 error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'KeyError'> Error Contents: 'premium_until' Traceback (most recent call last): File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.accountmgr/lib/startup.py", line 873, in <module> PremAccntNotification().run() File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.accountmgr/lib/startup.py", line 158, in run expires = datetime.fromtimestamp(account_info['premium_until']) ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'premium_until' -->End of Python script error report<--

This is the part which seems to be related to the error. (Just to save you a bit of time, the log is rather huge).

**Comment by Zaxxon709** [comment] 2024-12-04 13:30
First, I'd like to thank you for providing a log and a detailed description of the issue. 

This error is produced when the "Debrid Account Expiry Notification Service" is run. It's not an error to be concerned about and will not affect the use of your Premiumize account. 

I'm unable to reproduce the error but from what I can see it appears that the account info is not being pulled from the Premiumize API. Without the account information the total days left on your account cannot be obtained and this is why the error occurs. I'm not sure why this is happening but appears to be an issue on your end. Could you try a power cycle of your router. Then try revoking Premiumize and reauthorizing. Report back with the results.

**Comment by rizreflects** [comment] 2024-12-04 13:48
Thanks for the response. I've ran into a strange problem when revoking premiumize. It doesn't seem to work. I've tried revoking and then restarting Kodi, but it still shows as authorized. I tried about 3-4 times with no success. I've attached a video for you to view showing the problem first hand.

https://streamable.com/gza4p0

**Comment by Zaxxon709** [comment] 2024-12-04 16:06
I've found the issue! It appears this bug has been present for quite some time! Please install the below and test to confirm the problem is resolved. The issue was due to the setting window reopening and when you choose OK to close it saves back the current Premiumize data. 

[script.module.acctview.zip](https://github.com/user-attachments/files/18011055/script.module.acctview.zip)

**Comment by rizreflects** [comment] 2024-12-04 16:43
The update worked perfectly. Upon installing I was able to revoke without a problem. Once re-authorised, the error never reappeared. Thank you very much for this fast update.

**Comment by Zaxxon709** [comment] 2024-12-04 19:04
That's great! Thanks for testing. Enjoy!

**Closed** 2024-12-04 19:04 UTC
